FROM python:3.11-slim

WORKDIR /app

COPY requirements-runtime.txt .
RUN pip install --no-cache-dir -r requirements-runtime.txt

COPY app.py .
COPY model ./model

EXPOSE 8000

CMD ["python", "app.py"]
