apiVersion: apps/v1
kind: Deployment
metadata:
  name: income-flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: income-flask-app
  template:
    metadata:
      labels:
        app: income-flask-app
    spec:
      containers:
        - name: income-predictor
          image: mariamhsein/income-flask-app:latest # your image
          ports:
            - containerPort: 8000

    
---
apiVersion: v1
kind: Service
metadata:
  name: income-flask-service
spec:
  selector:
    app: income-flask-app
  ports:
    - protocol: TCP
      port: 8000
      nodePort: 30800
  type: NodePort
