apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: detect-age-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: detect-age-api
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50