---
apiVersion: v1
kind: Service
metadata:
  name: detect-age-api
spec:
  type: NodePort
  selector:
    app: detect-age-api
  ports:
    - port: 5000
      nodePort: 30600

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: detect-age-api
spec:
  replicas: 1  # Initial pod count; HPA will manage scaling
  selector:
    matchLabels:
      app: detect-age-api
  template:
    metadata:
      labels:
        app: detect-age-api
    spec:
      containers:
        - name: detect-age-api
          image: mariamhsein/age_detect:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "250m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"



